/**
 * generateReceiptPdf.ts
 * Generates a branded iWhistle PDF receipt for a single payment.
 */

interface ReceiptData {
  paymentId: string;
  amount: number;
  date: string;
  gameLabel: string;
  tournamentName: string;
  method: string;
  status: string;
}

export const generateReceiptPdf = async (data: ReceiptData): Promise<void> => {
  const jsPDF = (await import('jspdf')).default;
  const { format } = await import('date-fns');

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a5' });

  const DEEP_BLUE  = [0, 61, 122]    as [number, number, number];
  const ORANGE     = [255, 140, 0]    as [number, number, number];
  const WHITE      = [255, 255, 255]  as [number, number, number];
  const LIGHT_GREY = [245, 247, 250]  as [number, number, number];
  const TEXT_DARK  = [30, 41, 59]     as [number, number, number];
  const TEXT_MID   = [100, 116, 139]  as [number, number, number];
  const GREEN      = [22, 163, 74]    as [number, number, number];

  const pageW = doc.internal.pageSize.getWidth();
  const margin = 14;

  // Header
  doc.setFillColor(...DEEP_BLUE);
  doc.rect(0, 0, pageW, 30, 'F');
  doc.setTextColor(...WHITE);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text('iWhistle', margin, 12);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(180, 210, 235);
  doc.text('LEADERSHIP UNDER PRESSURE', margin, 18);
  doc.setTextColor(...WHITE);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('RECEIPT', pageW - margin, 12, { align: 'right' });
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(180, 210, 235);
  doc.text(`#${data.paymentId.slice(0, 12).toUpperCase()}`, pageW - margin, 19, { align: 'right' });
  doc.setFillColor(...ORANGE);
  doc.rect(0, 30, pageW, 2, 'F');

  // Amount block
  doc.setFillColor(...LIGHT_GREY);
  doc.rect(margin, 38, pageW - margin * 2, 22, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(24);
  doc.setTextColor(...TEXT_DARK);
  doc.text(`$${data.amount}`, pageW / 2, 52, { align: 'center' });
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...TEXT_MID);
  doc.text('PAYMENT AMOUNT', pageW / 2, 58, { align: 'center' });

  // Details
  const rows: [string, string][] = [
    ['Date', data.date ? format(new Date(data.date), 'MMMM d, yyyy') : '—'],
    ['Game', data.gameLabel],
    ['Tournament', data.tournamentName],
    ['Method', data.method || '—'],
    ['Status', data.status.charAt(0).toUpperCase() + data.status.slice(1)],
  ];

  let y = 72;
  rows.forEach(([label, value]) => {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(...TEXT_MID);
    doc.text(label, margin, y);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...TEXT_DARK);
    doc.text(value, pageW - margin, y, { align: 'right' });
    doc.setDrawColor(226, 232, 240);
    doc.line(margin, y + 2, pageW - margin, y + 2);
    y += 10;
  });

  // Status badge
  const statusColor = data.status === 'paid' ? GREEN : ([202, 138, 4] as [number, number, number]);
  doc.setFillColor(...statusColor);
  doc.roundedRect(margin, y + 4, 28, 7, 2, 2, 'F');
  doc.setTextColor(...WHITE);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.text(data.status.toUpperCase(), margin + 14, y + 9, { align: 'center' });

  // Footer
  const footerY = doc.internal.pageSize.getHeight() - 12;
  doc.setFillColor(...LIGHT_GREY);
  doc.rect(0, footerY - 4, pageW, 16, 'F');
  doc.setFontSize(7);
  doc.setTextColor(...TEXT_MID);
  doc.setFont('helvetica', 'normal');
  doc.text(
    `Generated by iWhistle on ${format(new Date(), 'MMMM d, yyyy')}`,
    pageW / 2, footerY + 3, { align: 'center' },
  );

  doc.save(`iWhistle_Receipt_${data.paymentId.slice(0, 8).toUpperCase()}.pdf`);
};
